group 'com.alexmercerind.media_kit_video'
version '1.0'

buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.13.0'
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

apply plugin: 'com.android.library'

android {
    namespace 'com.alexmercerind.media_kit_video'

    buildFeatures {
        buildConfig true
    }


    compileSdkVersion 36
    ndkVersion '28.2.13676358'

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        minSdkVersion 16
        buildConfigField 'int', 'MEDIA_KIT_TEXTURE_MAX_WIDTH',
                (project.findProperty('mediaKitTextureMaxWidth') ?: '0').toString()
        buildConfigField 'boolean', 'MEDIA_KIT_TEXTURE_CONSUMER_STATS',
                (project.findProperty('mediaKitTextureConsumerStats') ?: 'false').toString()
        consumerProguardFiles 'proguard-rules.pro'

        externalNativeBuild {
            cmake {
                cppFlags '-std=c++17'
            }
        }
    }

    externalNativeBuild {
        cmake {
            path file('src/main/cpp/CMakeLists.txt')
            version '3.22.1'
        }
    }
}
